version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
      #create another container for 'TEST'
  test-database:
    image: postgres:15.0
    container_name: test-database
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
networks:
  nestjs-network:

  #docker composer up -d
#docker rm -f dev-database
